import type { ObjectValues } from '../types/core';

export const ERROR_CODE = {
  // auth
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_OTP: 'INVALID_OTP',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',

  // contacts
  CANNOT_ADD_SELF: 'CANNOT_ADD_SELF',
  CONTACT_ALREADY_EXISTS: 'CONTACT_ALREADY_EXISTS',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',

  // calls / rooms
  CANNOT_CALL_SELF: 'CANNOT_CALL_SELF',
  USER_NOT_REACHABLE: 'USER_NOT_REACHABLE',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  CALL_NOT_FOUND: 'CALL_NOT_FOUND',

  // devices
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',

  // shared across routes
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = ObjectValues<typeof ERROR_CODE>;
